# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1af06e0a53a16011c51dc0e4190a17ec7128bab5451b5a81f7132f05e4b9a63133487ce31d024a88a4e4ec0296a0bb778ceafe5fcf4fc64a903c92f6105c9e9b

test:
  secret_key_base: cb54a83ee7cadf40e49cf4ae76eed82495101749875ad9ab46eb8910f60970024b0b15bebfdcac12f30cd93432b2da2a625403dac416c5dddd0445ad67475eda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
